version: '3.9'
services: 
    app:
        build:
            target: development
        volumes: 
            - ./app:/app:ro
        environment:            
            - NODE_ENV=development
        command: npm run dev
    dbui: 
        image: mongo-express
        ports: 
            - 8082:8081
        environment: 
            - ME_CONFIG_MONGODB_SERVER=db
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ADMIN_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ADMIN_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${DBUI_ADMIN_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${DBUI_ADMIN_PASSWORD}
        depends_on: 
            - db
